# Generated by Django 4.2.7 on 2023-11-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default=None, max_length=15)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'New Sentiment Monitoring Table',
            },
        ),
        migrations.CreateModel(
            name='TempImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='temp/sentiment_analysis/Image/')),
            ],
            options={
                'db_table': 'Temporary Images Sentiment Analysis',
            },
        ),
    ]
